### ISSUE TITLE
Support JSON Patch format

### ISSUE THREAD

**Issue by josephburnett** [josephburnett/jd#1]
Add support for rendering and reading diffs in JSON Patch format: https://tools.ietf.org/html/draft-ietf-appsawg-json-patch-10

**Comment by jpsim** [comment]
This would be 👌

**Comment by np** [comment]
A first step would be to emit objects of the form: `{path: PATH, old: OLD, new: NEW}` (instead of `@ PATH\n- OLD\n+ NEW"`)

**Comment by josephburnett** [comment]
Added `-f` flag to choose output format (https://github.com/josephburnett/jd/commit/52a000e20c09d5019947a7e2a9d29f20817d7aea).  A value of `patch` will output an [RFC 6901](https://datatracker.ietf.org/doc/html/rfc6901) JSON Patch.  Removal is done with `test` and `remove` ops because `jd` diffs are strict and expect a value to be present when removed.

**Comment by josephburnett** [comment]
I've closed this because I don't really intend on reading JSON Patch format diffs.  If you need it, please open a feature request issue.

**Comment by josephburnett** [comment]
Actually I want to add support for reading back the JSON Patch's that I write so I can add E2E tests and verify round-tripping.  So I'm opening this again until the E2E tests for JSON Patch are added.

**Comment by josephburnett** [comment]
Okay, I've added E2E tests.  And a translate function to turn `jd` diffs into JSON Patch format.  Here is an example of how to use this with `kubectl`: https://github.com/josephburnett/jd#see-what-changes-in-a-kuberentes-deployment
