### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by Billy-** [josephburnett/jd#11]
I downloaded the latest release and stuck in in `/usr/local/bin` and ran `chmod +x jd`. Trying to run it (in any way) results in `exec format error: jd`.

Did I install correctly? Do I need go installed to run this?

I'm on OSX.

🙇

**Comment by drjonnicholson** [comment]
I installed this using `asdf` (https://github.com/asdf-vm/asdf) without a problem... which is a cool project worth looking at.

If you install it all you need to do is:

```bash
asdf plugin-add golang
asdf install golang 1.12.1
asdf global golang 1.12.1
go get github.com/josephburnett/jd
```

You may need to reshim after installing if you can't run `jd`, which is easy as `asdf reshim golang`

**Comment by josephburnett** [comment]
> I'm on OSX

I built the binary for Linux.  You should build it from source instead.  Should be pretty straight forward since jd has no dependencies outside the standard library.

**Comment by Billy-** [comment]
> I installed this using asdf
That looked like it worked at first (install worked, global had no output but exited 0) but `go` is not found..
> You should build it from source instead
is that what installing go and running `go get github.com/josephburnett/jd` is?

**Comment by josephburnett** [comment]
Yes. Installing go for your platform (MacOS) and running `go get github.com/josephburnett/jd` will download the source code and built it. The `jd` binary will be in $GOPATH/bin, so you might need to add that directory to your $PATH variable.
