### ISSUE TITLE
Looking for a way to get only the changed values

### ISSUE THREAD

**Issue by seiferteric** [josephburnett/jd#17]
For my use case I was looking to use this library to get a json output with only the changed values between two inputs, but so far I have not been able to do so. Is there a way currently to do this? I tried applying the diff to an empty jsonNode object, but that does not work, also I looked for a way to iterate over each object recursively to do an Equals on each sub object to remove if they are equal, but can't seem to do that either.

**Comment by josephburnett** [comment]
> a json output with only the changed values between two inputs

Can you give me an example?  What should jd output when the changes are nested within several layers of structures?

> I looked for a way to iterate over each object recursively to do an Equals on each sub object to remove if they are equal

When you call [`.Diff()`](https://github.com/josephburnett/jd/blob/1f9071c800e7572a6844c86b272c71415c2e083e/lib/node.go#L13) on a `JsonNode` it will return a `Diff` which tells you which objects are different.  Is the information you want within that?

It would be helpful to see a concrete input (two structures) and the information you wish you could get (hypothetical output).  So I can understand better what you want to do with it.

**Comment by seiferteric** [comment]
Turns out I misread the requirement and don't need this functionality, thanks.
