### ISSUE TITLE
jd-tool.appspot.com needs a new version of go

### ISSUE THREAD

**Issue by ijoseph** [josephburnett/jd#24]
https://jd-tool.appspot.com/

> Go 1.9 is no longer available. Please refer to https://goo.gl/aESk5L for more information.

**Comment by josephburnett** [comment]
Thanks for noticing that!  Upgraded to 1.14: https://github.com/josephburnett/jd/commit/dac949bc81af4251550d0458596bd0368976d053

**Comment by josephburnett** [comment]
I've compiled the library into web assembly so it can run entirely in the browser, so I don't need to upgrade golang on App Engine again.  The new UI also renders the diff (or patch) on the fly so it's a little easier to play with: http://play.jd-tool.io/  @ijoseph take a look and tell me how it works for you.

**Comment by ijoseph** [comment]
Works pretty well! Did not know about WebAssembly either -- looks pretty neat.
