### ISSUE TITLE
Error: undefined: base64EncodedFiles

### ISSUE THREAD

**Issue by ritmas** [josephburnett/jd#28]
With the [latest commit](https://github.com/josephburnett/jd/commit/19e9fd8433ac29b88fcb6d594d70590b5d667ead) installation fails on `go1.15.2`:

```
# go version
go version go1.15.2 linux/amd64

# go get github.com/josephburnett/jd
# github.com/josephburnett/jd/web/serve
/root/go/src/github.com/josephburnett/jd/web/serve/serve.go:14:11: undefined: base64EncodedFiles
```

**Comment by josephburnett** [comment]
I just started including the web UI in the commandline tool.  It's 3 files base64 encoded into a goang source.  However that won't happen when you install with `go get`.  Requires `make pack-web` or another recipe which depends on it.

But you must be able to `go get` this tool.  So I've just checked in the compiled and packed UI.  I'll make sure to update it whenever I change the UI:  https://github.com/josephburnett/jd/commit/63d6811f752fd32f7f16d6d3686414067fb43006

Sorry about that!  Should be fixed at head now.

**Comment by josephburnett** [comment]
I figured out how to remove this generated file from version control without breaking `go get`.  https://github.com/josephburnett/jd/commit/05af9a9f74d509338136eacdf0c05bb9e7373397  But let me know if this causing any other problems.
