### ISSUE TITLE
Use return codes to signal whether a file is the same

### ISSUE THREAD

**Issue by nbenns** [josephburnett/jd#35]
When using this tool in scripts it would be nice to use standard program return codes to signal to the script via `$?` that a comparison is the same `0` or different `> 0`.

**Comment by nbenns** [comment]
Oh I see you have the feature, just not a release with it: https://github.com/josephburnett/jd/commit/9f4fdc30c118f33e8b39de8671807506c0bf7819

**Comment by josephburnett** [comment]
Yeah, there's a few more changes in progress.  I'll make a release when they are done.  Unless you need one sooner.

**Comment by josephburnett** [comment]
There are several features that will land in v1.5.0.  You can track the progress here: https://github.com/josephburnett/jd/projects/1
