### ISSUE TITLE
Binaries for Linux, Windows and macOS

### ISSUE THREAD

**Issue by gkjpettet** [josephburnett/jd#40]
I see that you release Dockerfiles for Linux, Windows and macOS. 

I was wondering, is it possible to release compiled binaries for these platforms instead? 

I'm not sure how to build the tool myself (not being a Go user). I've managed to install `jd` on macOS using Homebrew but I would like to include the binary in an app I'm building for Linux & Windows and I'm not sure how to ensure `jd` is installed.

**Comment by josephburnett** [comment]
Actually I do provide binaries for these platforms since v1.4.0.  I've just cut a new release so you can get the latest changes: https://github.com/josephburnett/jd/releases/tag/v1.5.1

Under artifacts you will find `jd-amd64-darwin` (macOS), `jd-amd64-linux` and `jd-amd64-windows`.  Let me know if you have any trouble running jd on your platform!  :)

**Comment by andreineculau** [comment]
@josephburnett any chance for arm64 binaries? 🚀

**Comment by josephburnett** [comment]
@andreineculau sure!  I've built arm64 binaries for the same set of OS's and uploaded them under assets in v1.5.1.  It's part of the release now so they will be there for subsequent versions too.  I don't have an arm64 device, so I couldn't test them.  Try it out and let me know if it works or not.

**Comment by andreineculau** [comment]
@josephburnett Thanks! 🙌

Seems to work, though you might have uploaded 1.5.0 binaries instead of 1.5.1 😉

**Comment by josephburnett** [comment]
@andreineculau whoops!  I forgot to get the version to 1.5.1 in main.go.  But the two binaries are identical.  I just cherry picked a change to skip docker build which bumped the version from 1.5.0 to 1.5.1.  I've just renamed the release to 1.5.0 so it's not confusing.  Thanks for noticing!
